[package]
name = "minecraft-info-bot"
version = "0.1.0"
authors = ["Marcus Ball <marcus@marcusball.me>"]

[dependencies]
minecraft-server-info = { git = "https://github.com/marcusball/minecraft-server-info" }
slack = "0.14.0"
